#!/usr/bin/env bash
# Convert medzotero skills to LLM-for-Zotero format (ultra-minimal for Agent Mode).
#
# LLM-for-Zotero uses `id` + `match` patterns, not the Claude Code `name` + `description`.
# Rather than maintaining a second copy of every skill here, this script DERIVES each
# Zotero file from its skills/<name>/SKILL.md (single source of truth):
#   - `id`    <- the SKILL.md frontmatter `name`
#   - `match` <- each entry under the frontmatter `zotero_match:` list
#   - body    <- the text between the `<!-- ZOTERO:START -->` / `<!-- ZOTERO:END -->` markers
#
# Edit the SKILL.md (frontmatter + ZOTERO block); never edit generated output by hand.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_SRC="$(cd "$SCRIPT_DIR/.." && pwd)/skills"
OUTPUT_DIR="${ZOTERO_DATA_DIR:-$HOME/Zotero}/llm-for-zotero/skills"

mkdir -p "$OUTPUT_DIR"

if [ ! -d "$SKILLS_SRC" ]; then
  echo "Error: skills directory not found at $SKILLS_SRC" >&2
  exit 1
fi

count=0
deployed_ids=()
for skill_md in "$SKILLS_SRC"/*/SKILL.md; do
  [ -f "$skill_md" ] || continue

  # id <- frontmatter `name:` (first occurrence)
  id="$(awk -F': *' '/^name:[[:space:]]/ {print $2; exit}' "$skill_md")"

  # match patterns <- items under `zotero_match:` (lines like `  - /foo/i`), stop at next key or `---`
  matches="$(awk '
    /^zotero_match:[[:space:]]*$/ {f=1; next}
    f && /^---[[:space:]]*$/      {f=0}
    f && /^[A-Za-z]/              {f=0}
    f && /^[[:space:]]*-[[:space:]]+/ {
      line=$0; sub(/^[[:space:]]*-[[:space:]]+/, "", line); print line
    }
  ' "$skill_md")"

  # body <- text between the ZOTERO markers
  body="$(awk '
    /<!-- ZOTERO:START -->/ {f=1; next}
    /<!-- ZOTERO:END -->/   {f=0}
    f                       {print}
  ' "$skill_md")"

  if [ -z "$id" ]; then
    echo "Skipping $skill_md: no frontmatter name:" >&2
    continue
  fi
  # id becomes a filename below; reject anything that could escape OUTPUT_DIR.
  if [[ ! "$id" =~ ^[a-z0-9][a-z0-9._-]*$ ]]; then
    echo "Skipping $skill_md: unsafe skill name '$id' (expected [a-z0-9._-])" >&2
    continue
  fi
  if [ -z "$matches" ]; then
    echo "Skipping $skill_md ($id): no zotero_match: patterns" >&2
    continue
  fi
  if [ -z "$body" ]; then
    echo "Skipping $skill_md ($id): no ZOTERO block" >&2
    continue
  fi

  out="$OUTPUT_DIR/$id.md"
  {
    echo "---"
    echo "id: $id"
    while IFS= read -r pattern; do
      [ -n "$pattern" ] && echo "match: $pattern"
    done <<< "$matches"
    echo "---"
    printf '%s\n' "$body"
  } > "$out"

  echo "Wrote $out"
  deployed_ids+=("$id")
  count=$((count + 1))
done

# Warn about *.md already in the output dir that this run did not generate.
# These may be stale (a renamed/removed skill) — but the dir can also hold the
# user's own skills, so we report rather than delete. Review and remove manually.
shopt -s nullglob
for existing in "$OUTPUT_DIR"/*.md; do
  base="$(basename "$existing" .md)"
  is_current=false
  for did in ${deployed_ids[@]+"${deployed_ids[@]}"}; do
    if [ "$base" = "$did" ]; then
      is_current=true
      break
    fi
  done
  if [ "$is_current" = false ]; then
    echo "Note: $existing was not generated by this run (orphaned/stale skill?). Remove it manually if obsolete." >&2
  fi
done
shopt -u nullglob

echo ""
echo "$count skill(s) deployed to $OUTPUT_DIR. Restart Zotero to load."
